hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activiation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("waybar")
	hl.exec_cmd("mako")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("hypridle")
end)
