"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$directory$git_branch$cmd_duration$status $character'

[directory]
style = 'white'
format = '[$path]($style)'
truncation_length = 1

[git_branch]
format = ' [git:$branch](dimmed white)'

[cmd_duration]
min_time = 5000
format = ' [$duration](dimmed white)'

[status]
disabled = false
format = ' [$status](red)'

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](white)'
