require("modules.monitors")
require("modules.environment")
require("modules.autostart")
require("modules.appearance")
require("modules.animations")
require("modules.input")
require("modules.bindings")
require("modules.windows")
