general {
    hide_cursor = true
}

background = {
    monitor = 
    color = rgba(111111ff)
}

input-field {
    monitor =
    size = 300, 50
    position = 0, 0
    outline_thickness = 1
    inner_color = rgba(202020ff)
    outer_color = rgba(777777ff)
    front_color = rgba(ffffffff)
}
