vim.opt.clipboard = "unnamedplus"
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = false
vim.opt.cursorcolumn = false
vim.opt.guicursor = "a:block-blinkon0"
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.opt.showtabline = 1
vim.opt.ruler = true
vim.opt.shortmess:append("I")
vim.opt.fillchars:append({ eob = " " })
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
